language: python
python:
- "3.7"
# setup environment
env:
- DJANGO_VERSION=2.0
- DJANGO_SETTINGS_MODULE='di_photouploader.settings.production'
# install dependencies
install:
- pip install -r requirements.txt

# run test scripts
script:
- python manage.py test 
